version: "3.8"


services:
  postgres:
    image: postgres
    container_name: dropbox_db
    restart: always
    environment:
      POSTGRES_DB: "dropbox_tgbot"
      POSTGRES_USER: "dropbox_user"
      POSTGRES_PASSWORD: "your_passwd"
    ports:
      - "5443:5432"
    networks:
      default:
        ipv4_address: 172.28.1.5

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dropbox_bot
    restart: always
    command: sh -c "python3 /home/Dropbox_API/bot_body.py"
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 172.28.1.4


networks:
    default:
      driver: bridge
      ipam:
        config:
          - subnet: 172.28.1.0/24
